---
title: "datacamp practice on books"
author: "Susan Hajmohammad"
date: "April 4, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(gutenbergr)
library(stringr)
library(dplyr)



```

```{r}

north_abby <- gutenberg_download(121)


```




```{r}



#north_abby <- as.matrix(north_abby)


abby_text <- north_abby %>%
  select(text, chapter)

```

Split up by chapter:

use a for loop:

```{r}

num_lines <- nrow(north_abby)

for (i in 1:num_lines) {
  
  north_abby$chapter[i] <- sum(str_detect(north_abby$text[1:i], pattern = fixed("CHAPTER"))) 
  
  
}




```



```{r}

#north_abby$chapter <- str_detect(north_abby, pattern = "chapter")



contains_ss <- str_detect(north_abby, pattern = fixed("ss"))

contains_ss

sum(contains_ss)

north_abby[contains_ss]

```



Practice word bank :
murder 
dark 
scary
ghost
dead
death
scream
blood
frightened



apply fuction 
on word bank 

```{r}

word_bank <- c("murder", "dark", "scary", "ghost", "dead", "death", "scream", "blood", "frightened")

# spooky_words <- str_detect(abby_text, pattern = c("murder", "dark", "scary", "ghost", "dead", "death", "scream", "blood", "frightened"))
# 
# sum(spooky_words)


spooky_words <- str_detect(abby_text, pattern = c("dark", "frightened"))

#xx <- lapply(spooky_words, str_detect())


dark <- str_detect(abby_text, pattern = "dark")

sum(dark)


frightened <- str_detect(abby_text, pattern = "frightened")

sum(frightened)




```


Create function: 



```{r}



count_string <- function(x){
  sum(str_detect(abby_text$text, x))
  
}


sapply(word_bank, count_string)

  
```







```{r}

  
  

# number_dark <- str_count(north_abby, pattern = "dark")
# 
# hist(number_dark)



murder <- str_detect(abby_text, pattern = "murder")

sum(murder)


scary <- str_detect(abby_text, pattern = "scary")

sum(scary)


ghost <- str_detect(abby_text, pattern = "ghost")

sum(ghost)


dead <- str_detect(abby_text, pattern = "dead")

sum(dead)


death <- str_detect(north_abby, pattern = "death")

sum(death)

scream <- str_detect(north_abby, pattern = "scream")

sum(scream)


blood <- str_detect(north_abby, pattern = "blood")

sum(blood)


```



character presence:


```{r}

Catherine <- str_detect(north_abby, pattern = "Catherine")

sum(Catherine)


```


```{r}

James <- str_detect(north_abby, pattern = "James")

sum(James)


```


He vs. She


```{r}

#abby_text <- as.matrix(abby_text)

he <- str_detect(abby_text, pattern = "he")

sum(he)


```

He by Chapter:


```{r}

library(tidyverse)

by_chap <- abby_text %>%
  group_by(chapter) %>%
  summarise(num_he = sum(str_detect(text, pattern = fixed(" he ", ignore_case = TRUE))))
  

by_chap


murder_chap <- abby_text %>%
  group_by(chapter) %>%
  summarise(num_he = sum(str_detect(text, pattern = fixed(" murder ", ignore_case = TRUE))))


murder_chap

  





```










```{r}

she <- str_detect(north_abby, pattern = "she")

sum(she)


```


There are four female characters and 6 male characters according to wiki <https://en.wikipedia.org/wiki/Northanger_Abbey#Characters>


Using str_split

```{r}


north_abby1 <- str_split(north_abby, pattern = fixed(" . "), simplify = TRUE)


head(north_abby1)



```



```{r}

library(rebus)

of <- char_class("of")

of

str_view(north_abby, pattern = of)



```


## Sentiment Anlysis: the tidy way:

Lexicons:

```{r}

library(dplyr)
library(tidytext)

get_sentiments("bing")





```




Splitting novel up by words: 


```{r}


library(tidytext)


abby_words <- abby_text%>%
  unnest_tokens(word, text)






```















