---
title: "SH Progress Notes"
author: "Your name(s)"
date: "Spring 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Week 6

Goals:

  long term:
  
  - Find the names mentioned close to each other in each novel
  - Find the adjectives closest to certain character names
  - THis would include looking for how to code to select the nearest 5 words around a character's name for example.  
  - FIrst figure out how to split the book into lines 
  - also look into pronouns because the character's name isn't always mentioned in the text.  This could show us a difference in mood when referring to women vs. men (she/her vs he/him).  
  
  SHort term: 
  - update the metadata
     do this by manually putting in the missing gothic books into a csv an rbind it to the df I have already made.  
  - the data frame should include all the info but ultimately be split up by chapter per row.  
  
  
Time: 



Summary:

Completed Intermediate R



# Week 

Goals:

  long term:
  
  -look through the themes of one or two gothic books, using information given to us by the gothic lit class.   
  
  Short term: 
  - complete data camp 
  
  
Time: 



Summary:

Completed Intermediate R
 



# Week 

Goals:

  
  - Practice stringr functions on a gothic book
  - complete data camp stringr course
  - Come up with a "spooky" word bank and try to find those words in a gothic book.  
  
  
Time: 



Summary:

Used functions from stringr on the Northanger Abby book. 
Used as.matrix() on the gutenbergr download object in order for these functions to work. \

I think I have Northanger abby split into chapters by using the str_detect function on "chapter" and adding it as a new column in the north_abby matrix.  

Questions: 

When I use the str_split() function to split the text into lines, specifying pattern = " . ", it gives me a weird output.  I specified simplify = TRUE so it would be a matrix.  









# Week 

Goals:

 long term:

group by chapter and count he or she by chpter, or other words

Shrt term

Spooky words


step 1

Str_detect, with one line of strdetect try to find the total number of any of those words.  
be able to pull out the number of any given spooky word. 

step 2

intro to tidyverse or r for data science ch5.  section on grouped summaries.  play around with what can I do if I group by chapter, total number of words or lines. 


      work on grouping by chapter, for example number of "he"


Play around with the data set. 


look at data camp tidy sentiment 
  built in lexicons, positive and negative
  word clouds. 
    which seems spooky.  
  
  
Time: 



Summary:

I attempted to use lapply to detect many strings at one time in the text.  I tried with both a word bank and with two sample words.  The problem I am running into is that I don't understand where "abby_text" should go into the function I am creating in the lapply function.  

On top of that I tried to get one of the str_detect functions to also group_by chapter and that is also not working for me.  I think it might have something to do with the format of the data.  I remember when we were talking about how I put the data as a matrix initially but this would include the column with the book ID.  Well the problem I am having is that in order to group_by I need the chapter column, however when I include the chapter column the text is no longer in a form that I can use str_detect on it.  I also tried putting the df with text and chapter as a matrix and this also did not work.  I think this is because the data in the chapter column would mix in with the text.  


I want to work on doing an "innerjoin" with this text and the "bing" lexicon.  




Goals:



* rather than doing new stuff, consolidate what I have.  Work to get it more organized.  
Put into a more smaller doc. 


Get abby novel, create abby txt w chapters, create abby words w unnest tokens, group by chapter and summarize.

Do as many variables num_he, num_dark




Goals:


x put packages in set up, because include = false.

x abby_words earlier on to count many words in a line.  


- play around with ways to visualize the words by chapter, diff types of graphs, 
- Make a word cloud overall by book or by chapter, 
- Look up datacamp on how to make word cloud




